### PR TITLE
New --config option for the rails_best_practices command 

### PR DESCRIPTION
**Pull request by mensfeld**
Same reason as here: https://github.com/railsbp/rails_best_practices/pull/99 - just working and without conflicts

### CODE REVIEW

**Comment by mensfeld** [comment]
Had to freeze rake to make travis run + added +1 to class length to match the extended class definition ;)

**Comment by mensfeld** [comment]
Hey @flyerhzm  thank you for merging. Do you have some ETA for the next release of the gem? Due to my usecase I can't use github version and I'm "forced" to used gemed one. I would love to know if you guys are planning to release 1.17.1 soon. Thank you!

**Comment by flyerhzm** [comment]
@mensfeld I just released 1.18.0, thanks for your contribution.

**Comment by mensfeld** [comment]
@flyerhzm no, thank you for maintaining this great tool! :-)

**Pull request merged**
